// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxiocwtfejvgtupqtcnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4aW9jd3RmZWp2Z3R1cHF0Y254Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4NzU1MjAsImV4cCI6MjA1MjQ1MTUyMH0.AkGL3qHYwII-G63dRdYT65008kMWIgcuPHlu1SYmPDA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);